include ../../Makefile.inc

all: cache-line.o cache-set.o cache.o
	
cache-line.o:
	$(CC) $(FLAGS) -c cache-line.cpp
	
cache-set.o:
	$(CC) $(FLAGS) -c cache-set.cpp
	
cache.o:
	$(CC) $(FLAGS) -c cache.cpp  
	